
# defaults file for roles/prometheus
---
prometheus_version: "2.55.1"
prometheus_port: 9090

prometheus_user: prometheus
prometheus_group: prometheus

prometheus_install_dir: /opt/prometheus
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus

prometheus_config_file: /etc/prometheus/prometheus.yml